In [1]:
import numpy as np

In [2]:
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Trigonometric sine, element-wise.
    
    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the de

In [3]:
np.info(np.sin)

sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Trigonometric sine, element-wise.

Parameters
----------
x : array_like
    Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
**kw

In [17]:
type(np.sin)


numpy.ufunc

In [5]:
data = np.ones(10)



In [8]:
data_2 = data[:, np.newaxis]

In [9]:
data_2.shape

(10, 1)

In [10]:
data_2.ravel()


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
data_2[5,0] =10

In [15]:
data[np.ones(10, dtype=np.bool)]

/tmp/ipykernel_225929/377745527.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data[np.ones(10, dtype=np.bool)]


array([ 1.,  1.,  1.,  1.,  1., 10.,  1.,  1.,  1.,  1.])

In [16]:
data[np.zeros(10, dtype=np.bool)]


/tmp/ipykernel_225929/1739956453.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data[np.zeros(10, dtype=np.bool)]


array([], dtype=float64)

In [18]:
import math
my_sin = np.vectorize(math.sin)


In [19]:
my_sin(np.ones(10))

array([0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098])

In [20]:
data[np.logical_and(np.arange(0,2, 10) > 0.5, np.arange(0,2, 10) < 1.5) ]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 1